<?php

namespace App\DTO\Integrations\Odoo\Order;

use App\Integrations\Odoo;
use App\Models\Order;
use Illuminate\Support\Facades\Log;
use Throwable;

class OrderDTO
{
    public function __construct(
        public readonly string $provider,
        public readonly int $providerId,
        public readonly string $name,
        public readonly ?string $number,
        public readonly int $clientId,
        public readonly string $clientName,
        public readonly int $partnerInvoiceId,
        public readonly int $partnerShippingId,
        public readonly string $date,
        public readonly ?string $createDate,
        public readonly ?string $writeDate,
        public readonly ?string $commitmentDate,
        public readonly ?string $validityDate,
        public readonly ?string $expectedDate,
        public readonly string $state,
        public readonly string $typeName,
        public readonly bool $locked,
        public readonly string $invoiceStatus,
        public readonly ?string $deliveryStatus,
        public readonly string $pickingPolicy,
        public readonly float $amountUntaxed,
        public readonly float $amountTax,
        public readonly float $amountTotal,
        public readonly float $amountToInvoice,
        public readonly float $amountInvoiced,
        public readonly float $amountPaid,
        public readonly float $amountUndiscounted,
        public readonly int $currencyId,
        public readonly string $currency,
        public readonly float $currencyRate,
        public readonly ?string $origin,
        public readonly ?string $reference,
        public readonly ?string $note,
        public readonly string $countryCode,
        public readonly ?int $userId,
        public readonly ?string $userName,
        public readonly ?int $teamId,
        public readonly ?string $teamName,
        public readonly int $warehouseId,
        public readonly string $warehouseName,
        public readonly int $companyId,
        public readonly string $companyName,
        public readonly int $invoiceCount,
        public readonly int $deliveryCount,
        public readonly bool $requirePayment,
        public readonly bool $requireSignature,
        public readonly float $prepaymentPercent,
        public readonly array $orderLine,
        public readonly array $tagIds,
        public readonly array $invoiceIds,
        public readonly array $pickingIds,
    ) {}

    public static function handle(array $o): self {
        try {
            return new self(
                provider: Odoo::$code,
                providerId: $o['id'],
                name: $o['name'],
                number: $o['client_order_ref'] ?: null,
                clientId: $o['partner_id'][0],
                clientName: $o['partner_id'][1],
                partnerInvoiceId: $o['partner_invoice_id'][0],
                partnerShippingId: $o['partner_shipping_id'][0],
                date: $o['date_order'],
                createDate: $o['create_date'] ?: null,
                writeDate: $o['write_date'] ?: null,
                commitmentDate: $o['commitment_date'] ?: null,
                validityDate: $o['validity_date'] ?: null,
                expectedDate: $o['expected_date'] ?: null,
                state: $o['state'],
                typeName: $o['type_name'],
                locked: $o['locked'],
                invoiceStatus: $o['invoice_status'],
                deliveryStatus: $o['delivery_status'] ?: null,
                pickingPolicy: $o['picking_policy'],
                amountUntaxed: $o['amount_untaxed'],
                amountTax: $o['amount_tax'],
                amountTotal: $o['amount_total'],
                amountToInvoice: $o['amount_to_invoice'],
                amountInvoiced: $o['amount_invoiced'],
                amountPaid: $o['amount_paid'],
                amountUndiscounted: $o['amount_undiscounted'],
                currencyId: $o['currency_id'][0],
                currency: $o['currency_id'][1],
                currencyRate: $o['currency_rate'],
                origin: $o['origin'] ?: null,
                reference: $o['reference'] ?: null,
                note: $o['note'] ?: null,
                countryCode: $o['country_code'],
                userId: $o['user_id'] ? $o['user_id'][0] : null,
                userName: $o['user_id'] ? $o['user_id'][1] : null,
                teamId: $o['team_id'] ? $o['team_id'][0] : null,
                teamName: $o['team_id'] ? $o['team_id'][1] : null,
                warehouseId: $o['warehouse_id'][0],
                warehouseName: $o['warehouse_id'][1],
                companyId: $o['company_id'][0],
                companyName: $o['company_id'][1],
                invoiceCount: $o['invoice_count'],
                deliveryCount: $o['delivery_count'],
                requirePayment: $o['require_payment'],
                requireSignature: $o['require_signature'],
                prepaymentPercent: $o['prepayment_percent'],
                orderLine: $o['order_line'] ?? [],
                tagIds: $o['tag_ids'] ?? [],
                invoiceIds: $o['invoice_ids'] ?? [],
                pickingIds: $o['picking_ids'] ?? [],
            );
        } catch (Throwable $e) {
            Log::channel('odoo.general')->error('Error handling order DTO: '.$e->getMessage(), [
                'order' => $o,
                'file' => $e->getFile(),
                'line' => $e->getLine(),
            ]);
            throw $e;
        }
    }
    public function toArray(): array {
        return [
            'provider' => $this->provider,
            'provider_id' => $this->providerId,
            'name' => $this->name,
            'number' => $this->number,
            'client_id' => $this->clientId,
            'client_name' => $this->clientName,
            'partner_invoice_id' => $this->partnerInvoiceId,
            'partner_shipping_id' => $this->partnerShippingId,
            'date' => $this->date,
            'create_date' => $this->createDate,
            'write_date' => $this->writeDate,
            'commitment_date' => $this->commitmentDate,
            'validity_date' => $this->validityDate,
            'expected_date' => $this->expectedDate,
            'state' => $this->state,
            'type_name' => $this->typeName,
            'locked' => $this->locked,
            'invoice_status' => $this->invoiceStatus,
            'delivery_status' => $this->deliveryStatus,
            'picking_policy' => $this->pickingPolicy,
            'amount_untaxed' => $this->amountUntaxed,
            'amount_tax' => $this->amountTax,
            'amount_total' => $this->amountTotal,
            'amount_to_invoice' => $this->amountToInvoice,
            'amount_invoiced' => $this->amountInvoiced,
            'amount_paid' => $this->amountPaid,
            'amount_undiscounted' => $this->amountUndiscounted,
            'currency_id' => $this->currencyId,
            'currency' => $this->currency,
            'currency_rate' => $this->currencyRate,
            'payment_status' => $this->getPaymentStatus(),
            'origin' => $this->origin,
            'reference' => $this->reference,
            'note' => $this->note,
            'country_code' => $this->countryCode,
            'user_id' => $this->userId,
            'user_name' => $this->userName,
            'team_id' => $this->teamId,
            'team_name' => $this->teamName,
            'warehouse_id' => $this->warehouseId,
            'warehouse_name' => $this->warehouseName,
            'company_id' => $this->companyId,
            'company_name' => $this->companyName,
            'invoice_count' => $this->invoiceCount,
            'delivery_count' => $this->deliveryCount,
            'require_payment' => $this->requirePayment,
            'require_signature' => $this->requireSignature,
            'prepayment_percent' => $this->prepaymentPercent,
            'order_line' => $this->orderLine,
            'tag_ids' => $this->tagIds,
            'invoice_ids' => $this->invoiceIds,
            'picking_ids' => $this->pickingIds,
        ];
    }
    public function getPaymentStatus(): string {
        return match (true) {
            $this->amountPaid >= $this->amountTotal => Order::PAYMENT_STATUS_APPROVED,
            $this->invoiceStatus === 'invoiced' => Order::PAYMENT_STATUS_APPROVED,
            default => Order::PAYMENT_STATUS_PENDING,
        };
    }
}
