<?php

return [
    [
        'section' => [
            'name' => 'Dashboard',
            'modules' => [
                [
                    'name' => 'Dashboards',
                    'icon' => 'fa-duotone fa-solid fa-chart-line-up',
                    'urlName' => null,
                    'active' => 'admin.dashboard*',
                    'canany' => [null, 'ordenes', 'blog', 'correos'],
                    'submodules' => [
                        [
                            'name' => 'General',
                            'urlName' => 'admin.dashboard.general.index',
                            'active' => 'admin.dashboard.general*',
                            'canany' => [null],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'E-Commerce',
                            'urlName' => 'admin.dashboard.order.index',
                            'active' => 'admin.dashboard.order*',
                            'canany' => ['ordenes'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Providers',
                            'urlName' => 'admin.dashboard.provider.index',
                            'active' => 'admin.dashboard.provider*',
                            'canany' => ['ordenes'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Blog',
                            'urlName' => 'admin.dashboard.blog.index',
                            'active' => 'admin.dashboard.blog*',
                            'canany' => ['blog'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Webmails',
                            'urlName' => 'admin.dashboard.email-web.index',
                            'active' => 'admin.dashboard.email-web*',
                            'canany' => ['correos'],
                            'submodules' => [],
                        ],
                    ],
                ],
            ],
        ],
    ],
    [
        'section' => [
            'name' => 'Web',
            'modules' => [
                [
                    'name' => 'Banner',
                    'icon' => 'fa-light fa-presentation-screen',
                    'urlName' => 'admin.banner.index',
                    'active' => 'admin.banner*',
                    'canany' => ['banners'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Gallery',
                    'icon' => 'fa-light fa-images',
                    'urlName' => 'admin.gallery.index',
                    'active' => 'admin.gallery*',
                    'canany' => ['galería'],
                    'submodules' => [],
                ],
                [
                    'name' => 'About',
                    'icon' => 'fa-light fa-building',
                    'urlName' => 'admin.about.index',
                    'active' => 'admin.about*',
                    'canany' => ['nosotros'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Partners',
                    'icon' => 'fa-light fa-handshake',
                    'urlName' => 'admin.partner.index',
                    'active' => 'admin.partner*',
                    'canany' => ['socios'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Team',
                    'icon' => 'fa-light fa-user-group',
                    'urlName' => 'admin.team.index',
                    'active' => 'admin.team*',
                    'canany' => ['team'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Videos',
                    'icon' => 'fa-light fa-video',
                    'urlName' => 'admin.video.index',
                    'active' => 'admin.video*',
                    'canany' => ['videos'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Services',
                    'icon' => 'fa-light fa-concierge-bell',
                    'urlName' => 'admin.service.index',
                    'active' => 'admin.service*',
                    'canany' => ['servicios'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Portfolio',
                    'icon' => 'fa-light fa-folder-open',
                    'urlName' => 'admin.portfolio.index',
                    'active' => 'admin.portfolio*',
                    'canany' => ['portafolio'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Packages',
                    'icon' => 'fa-light fa-boxes-stacked',
                    'urlName' => null,
                    'active' => 'admin.package*',
                    'canany' => ['paquetes', 'paquetes características'],
                    'submodules' => [
                        [
                            'name' => 'Packages',
                            'urlName' => 'admin.package.package.index',
                            'active' => 'admin.package.package*',
                            'canany' => ['paquetes'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Characteristics',
                            'urlName' => 'admin.package.feature.index',
                            'active' => 'admin.package.feature*',
                            'canany' => ['paquetes características'],
                            'submodules' => [],
                        ],
                    ],
                ],
                [
                    'name' => 'Testimonies',
                    'icon' => 'fa-light fa-quote-right',
                    'urlName' => 'admin.testimony.index',
                    'active' => 'admin.testimony*',
                    'canany' => ['testimonios'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Frequent questions',
                    'icon' => 'fa-light fa-messages-question',
                    'urlName' => 'admin.question-answer.index',
                    'active' => 'admin.question-answer*',
                    'canany' => ['preguntas y respuestas'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Newsletter',
                    'icon' => 'fa-light fa-user-check',
                    'urlName' => 'admin.newsletter.index',
                    'active' => 'admin.newsletter*',
                    'canany' => ['newsletter'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Webmails',
                    'icon' => 'fa-light fa-envelope-open-text',
                    'urlName' => 'admin.email-web.index',
                    'active' => 'admin.email-web*',
                    'canany' => ['correos'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Blog',
                    'icon' => 'fa-light fa-newspaper',
                    'urlName' => null,
                    'active' => 'admin.blog*',
                    'canany' => ['blog', 'blog categorías', 'blog etiquetas'],
                    'submodules' => [
                        [
                            'name' => 'Posts',
                            'urlName' => 'admin.blog.post.index',
                            'active' => 'admin.blog.post*',
                            'canany' => ['blog'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Categories',
                            'urlName' => 'admin.blog.category.index',
                            'active' => 'admin.blog.category*',
                            'canany' => ['blog categorías'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Tags',
                            'urlName' => 'admin.blog.tag.index',
                            'active' => 'admin.blog.tag*',
                            'canany' => ['blog etiquetas'],
                            'submodules' => [],
                        ],
                    ],
                ],
                [
                    'name' => 'Chatbot',
                    'icon' => 'fa-light fa-messages',
                    'urlName' => 'admin.chatbot.index',
                    'active' => 'admin.chatbot*',
                    'canany' => ['chatbot'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Questionnaire',
                    'icon' => 'fa-light fa-messages',
                    'urlName' => 'admin.questionnaire.index',
                    'active' => 'admin.questionnaire*',
                    'canany' => ['cuestionarios'],
                    'submodules' => [],
                ],
            ],
        ],
    ],
    [
        'section' => [
            'name' => 'E-Commerce',
            'modules' => [
                [
                    'name' => 'Invoices',
                    'icon' => 'fa-light fa-file-invoice-dollar',
                    'urlName' => null,
                    'active' => 'admin.invoice*',
                    'canany' => ['facturas'],
                    'submodules' => [
                        [
                            'name' => 'Invoices',
                            'urlName' => 'admin.invoice.invoice.index',
                            'active' => 'admin.invoice.invoice*',
                            'canany' => ['facturas'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Uses of cfdi',
                            'urlName' => 'admin.invoice.use-cfdi.index',
                            'active' => 'admin.invoice.use-cfdi*',
                            'canany' => ['facturas usos de cfdi'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Regimenes',
                            'urlName' => 'admin.invoice.fiscal-regime.index',
                            'active' => 'admin.invoice.fiscal-regime*',
                            'canany' => ['facturas regimenes'],
                            'submodules' => [],
                        ],
                    ],
                ],
                [
                    'name' => 'Orders',
                    'icon' => 'fa-light fa-basket-shopping',
                    'urlName' => 'admin.order.index',
                    'active' => 'admin.order*',
                    'canany' => ['ordenes'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Catalog',
                    'icon' => 'fa-light fa-shelves',
                    'urlName' => null,
                    'active' => 'admin.catalog*',
                    'canany' => ['productos', 'producto categorías', 'producto marcas', 'producto géneros'],
                    'submodules' => [
                        [
                            'name' => 'Products',
                            'urlName' => 'admin.catalog.product.index',
                            'active' => 'admin.catalog.product*',
                            'canany' => ['productos'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Warehouses',
                            'urlName' => 'admin.catalog.warehouse.index',
                            'active' => 'admin.catalog.warehouse*',
                            'canany' => ['producto almacenes'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Categories',
                            'urlName' => 'admin.catalog.category.index',
                            'active' => 'admin.catalog.category*',
                            'canany' => ['producto categorías'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Brands',
                            'urlName' => 'admin.catalog.brand.index',
                            'active' => 'admin.catalog.brand*',
                            'canany' => ['producto marcas'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Genders',
                            'urlName' => 'admin.catalog.gender.index',
                            'active' => 'admin.catalog.gender*',
                            'canany' => ['producto géneros'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Unit types',
                            'urlName' => 'admin.catalog.unit-type.index',
                            'active' => 'admin.catalog.unit-type*',
                            'canany' => ['tipos de unidades'],
                            'submodules' => [],
                        ],
                    ],
                ],
                [
                    'name' => 'Configurator PC',
                    'icon' => 'fa-light fa-computer',
                    'urlName' => null,
                    'active' => 'admin.configurator*',
                    'canany' => ['configurador pasos', 'configurador compatibilidades', 'configurador rendimiento'],
                    'submodules' => [
                        [
                            'name' => 'Stages',
                            'urlName' => 'admin.configurator.stage.index',
                            'active' => 'admin.configurator.stage*',
                            'canany' => ['configurador pasos'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Compatibilities',
                            'urlName' => 'admin.configurator.compatibility.index',
                            'active' => 'admin.configurator.compatibility*',
                            'canany' => ['configurador compatibilidades'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Budgets',
                            'urlName' => 'admin.configurator.budget.index',
                            'active' => 'admin.configurator.budget*',
                            'canany' => ['configurador rangos'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Rendimientos',
                            'urlName' => 'admin.configurator.performance.index',
                            'active' => 'admin.configurator.performance*',
                            'canany' => ['configurador rendimiento'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'Juegos',
                            'urlName' => 'admin.configurator.game.index',
                            'active' => 'admin.configurator.game*',
                            'canany' => ['configurador juegos'],
                            'submodules' => [],
                        ],
                        [
                            'name' => 'FPS',
                            'urlName' => 'admin.configurator.fps.index',
                            'active' => 'admin.configurator.fps*',
                            'canany' => ['configurador fps'],
                            'submodules' => [],
                        ],
                    ],
                ],
                [
                    'name' => 'Wholesale',
                    'icon' => 'fa-light fa-warehouse',
                    'urlName' => 'admin.wholesale.index',
                    'active' => 'admin.wholesale.*',
                    'canany' => ['mayoreo'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Promotions',
                    'icon' => 'fa-light fa-badge-percent',
                    'urlName' => 'admin.promotion.index',
                    'active' => 'admin.promotion.*',
                    'canany' => ['promociones'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Coupons',
                    'icon' => 'fa-light fa-ticket',
                    'urlName' => 'admin.coupon.index',
                    'active' => 'admin.coupon.*',
                    'canany' => ['cupones'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Shipping zones',
                    'icon' => 'fa-light fa-truck-fast',
                    'urlName' => 'admin.setting.shipping-zone.index',
                    'active' => 'admin.setting.shipping-zone*',
                    'canany' => ['zonas de envío'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Shipping classes',
                    'icon' => 'fa-light fa-tags',
                    'urlName' => 'admin.setting.shipping-class',
                    'active' => 'admin.setting.shipping-class',
                    'canany' => ['clases de envío'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Countries',
                    'icon' => 'fa-light fa-globe',
                    'urlName' => 'admin.setting.country',
                    'active' => 'admin.setting.country',
                    'canany' => ['países'],
                    'submodules' => [],
                ],
                [
                    'name' => 'States',
                    'icon' => 'fa-light fa-map-location-dot',
                    'urlName' => 'admin.setting.state',
                    'active' => 'admin.setting.state',
                    'canany' => ['estados'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Cities',
                    'icon' => 'fa-light fa-city',
                    'urlName' => 'admin.setting.city',
                    'active' => 'admin.setting.city',
                    'canany' => ['ciudades'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Analytic search',
                    'icon' => 'fa-light fa-chart-mixed',
                    'urlName' => 'admin.analytic-search.index',
                    'active' => 'admin.analytic-search*',
                    'canany' => ['analytic search'],
                    'submodules' => [],
                ],
            ],
        ],
    ],
    [
        'section' => [
            'name' => 'Subscripciones',
            'modules' => [
                [
                    'name' => 'Listado',
                    'icon' => 'fa-light fa-wallet',
                    'urlName' => 'admin.subscription.subscription.index',
                    'active' => 'admin.subscription.subscription.index',
                    'canany' => ['subscripciones'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Planes',
                    'icon' => 'fa-light fa-layer-group',
                    'urlName' => 'admin.subscription.plan.index',
                    'active' => 'admin.subscription.plan.*',
                    'canany' => ['subscripciones'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Características',
                    'icon' => 'fa-light fa-list-check',
                    'urlName' => 'admin.subscription.plan-feature.index',
                    'active' => 'admin.subscription.plan-feature*',
                    'canany' => ['subscripciones'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Mis Subscripciones',
                    'icon' => 'fa-light fa-credit-card',
                    'urlName' => 'admin.subscription.billing.index',
                    'active' => 'admin.subscription.billing.index',
                    'canany' => [null],
                    'submodules' => [],
                ],
            ],
        ],
    ],
    [
        'section' => [
            'name' => 'Settings',
            'modules' => [
                [
                    'name' => 'Users',
                    'icon' => 'fa-light fa-users',
                    'urlName' => 'admin.user.index',
                    'active' => 'admin.user*',
                    'canany' => ['usuarios'],
                    'submodules' => [],
                ],
                [
                    'name' => 'Configuration',
                    'icon' => 'fa-light fa-sliders',
                    'urlName' => 'admin.setting.welcome',
                    'active' => 'admin.setting*',
                    'canany' => [null],
                    'submodules' => [],
                ],
                [
                    'name' => 'Pulse',
                    'icon' => 'fa-light fa-heart-pulse',
                    'urlName' => 'admin.pulse.index',
                    'active' => 'admin.pulse*',
                    'canany' => ['pulse'],
                    'submodules' => [],
                ],
            ],
        ],
    ],
];
